### PR TITLE
Marco/dev — Add 'image_slice_offset' as an arg to 'project'

### PR DESCRIPTION
**Pull request by bommaritom**
These changes include the previously discussed changes to cone3D.py, as well as two other minor changes I've made in passing. Namely I added comments to a "test" file I had created in the past, and I added some text to some .rst (read-the-docs) files.

- cone3D.py: Add `image_slice_offset=0.0` to `project` arguments. Add corresponding functionality on lines 641-642.
- test_forward_proj.py: Add explanatory comments and print statements, add comments to code body.
- clean_install.rst, theory.rst: Add explanation of `dev_scripts`; copy-paste MBIR theory explanation from svmbir.

Tested: demo_3D_shepp_logan.py, demo_mace3D_fast.py, install_docs.sh

### CODE REVIEW

**Comment by dyang37** [comment]
Tested both the shepp Logan demo and readthedocs. Everything works fine.
@cabouman Can we merge this in ASAP?

**Comment by cabouman** [comment]
Marco, did you test the functionality of the new `image_slice_offset` argument in order to make sure it functions properly?

**Comment by bommaritom** [comment]
Hey Bouman, I have a demo file that runs a forward projection both without image_slice_offset set, with a positive value for image_slice_offset, and with a negative value for image_slice_offset. This demo file behaves as expected. I can add this demo file to the pull request if necessary.

**Comment by cabouman** [comment]
That's OK. I ran some test scripts, and it ran fine. I just wanted to make sure that you had tested the new feature.

**Pull request merged**
