### PR TITLE
Add comments in reference to Balke et al: "Separable Models for cone-beam MBIR Reconstruction".

### PR DESCRIPTION
**Pull request by bommaritom**
**Source Paper: [ei2018-Thilo.pdf](https://github.com/cabouman/mbircone/files/9365112/ei2018-Thilo.pdf)**

- Add comments to computeSysMatrix.c and icd3d.c, no changes to code.
- Ran demo/demo_3D_shepp_logan.py to verify that nothing has been affected in the code.

### CODE REVIEW

**Comment by dyang37** [comment]
Hey Marco, in the future could you please PR from an mbircone branch, instead of a forked repo branch? This will make testing easier.

**Review by dyang37 — APPROVED** [review]
I created a branch `marco_pr` that mirrors the code from the forked repo, in case anyone wants to test the PR.
Ran `demo_3D_shepp_logan.py` and results are visually the same as before.

**Comment by dyang37** [comment]
I'll go ahead and merge this PR since it's tested and only involves change in the comments.

**Comment by gbuzzard** [comment]
Nice work!  Thanks!
________________________________

**Pull request merged**
