### PR TITLE
Hotfix docs demos

### PR DESCRIPTION
**Pull request by bommaritom**
Hi all,

This is a 'hotfix' to my recent pull request that had some unfinished business.

Changes:

- update the cone3D.rst file and made some changes to the dosctrings. 
- remove deprecated methods extract_roi_from_roi, pad_roi2ror
- add a point-spread test file to the demo suite

I started to create a 'test' suite, but a test suite would need to access the 'demo_utils' module in order to run.  So, I have left 'debug_forward_proj.py' in the demo suite, knowing that it _should_ be divided out into its own suite that also has access to 'demo_utils'.

**Note that the multinode demo files still need to be updated and tested, since they previously relied on methods that are now deprecated.**

### CODE REVIEW

**Comment by dyang37** [comment]
Thanks Marco. I'll test this later in the afternoon.
Regards,
Diyu
________________________________

**Comment by cabouman** [comment]
Diyu, did you test the multinode demo?

**Comment by dyang37** [comment]
> Diyu, did you test the multinode demo?

Yes. I'm modifying the multinode script so that it is both compatible with recent changes due to ROR computation, and also matches with the style of the 3D shepp Logan demo (except for the multinode part).

I'll notify you when the testing is finished.

**Comment by dyang37** [comment]
Everything has been tested. I think it is OK to accept the PR at this point.

**Comment by cabouman** [comment]
Oh Shoot! I forgot to push my fixes before I accepted the PR. I'm going to have to do another PR fix.

**Comment by cabouman** [comment]
OK, you shouldn't ever do what I just did. I had to merge in the fixes, and then do a direct push into the master branch.

**Pull request merged**
