### PR TITLE
Multires

### PR DESCRIPTION
**Pull request by dyang37**
Test results and algorithm overview: [multi_res.pptx](https://github.com/cabouman/mbircone/files/9302609/multi_res.pptx)

I also tested with different image pixel pitch values. When setting `delta_pixel_image=2.0*delta_pixel_detector/magnification` (2x the default pixel pitch), I'm getting some funky recon results as shown below:
recon_axial

**This funky results is NOT introduced by multi-resolution, because I'm getting the same recon results with and without multi-resolution.** 

**Given the test results, I think it is okay to merge multi-res into master.**

We need to dig in further and figure out what's causing the results shown above when image pixel pitch is set to twice the default value, but that's another topic.

### CODE REVIEW

**Comment by cabouman** [comment]
Yes, I agree. This funky result is important, but we need to do one thing at a time.

**Comment by gbuzzard** [comment]
But please open an issue to describe this.

Greg
________________________________

**Comment by dyang37** [comment]
Issue opened: https://github.com/cabouman/mbircone/issues/85
[https://opengraph.githubassets.com/7bf3e61496c956db9581090f5bbc1bbeebf50a95562666e94bf484858963f44c/cabouman/mbircone/issues/85]<https://github.com/cabouman/mbircone/issues/85>
3D shepp Logan demo, customized pixel pitch value results in artifacts · Issue #85 · cabouman/mbircone<https://github.com/cabouman/mbircone/issues/85>
In demo_3D_shepp_logan.py, artifacts occurs when performing recon on non-default image pixel pitch values. recon results with delta_pixel_image=2.0*delta_pixel_detector/magnification: recon results...
github.com

Diyu
________________________________

**Comment by cabouman** [comment]
At this point, I think this multi resolution code looks good to me, so I'm going to accept the PR.

I added a demo so we can try reconstructing with variable pixel pitch. We can use this to further investigate what is going on with the forward projector.

**Pull request merged**
